services:
  api:
    build:
      context: ./schedule
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development

  client:
    build:
      context: ./front-schedule-best
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
